from youtube_transcript_api import YouTubeTranscriptApi
import json
import os

video_id = '-oTq-FfOsBk' #'c85AhmKL-_8' #"eatc50y785I"
lang = ['en']

transcript_list = YouTubeTranscriptApi.get_transcript(video_id)#, languages=lang)

#print (transcript_list)
f = open(video_id+".txt", "a")
for transcript in transcript_list:
    #print( json.dumps(transcript, separators=(',', ':')) )
    f.write(transcript["text"]+"\n")
    
f.close()

os.system('pause')

"""


transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
transcript = transcript_list.find_generated_transcript(['it', 'sp'])
print(transcript.fetch())


for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    print(transcript.translate('en').fetch())
"""